import { jsPDF } from "jspdf";

export type CertificateData = {
  firmName: string;
  userEmail: string;
  scanDate: string;
  totalFiles: number;
  filesScanned: number;
  allClean: boolean;
  verificationMethod: string;
};

export function generateCertificatePDF(data: CertificateData): Buffer {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Border
  doc.setDrawColor(0, 100, 180);
  doc.setLineWidth(2);
  doc.rect(10, 10, pageWidth - 20, pageHeight - 20);
  doc.setLineWidth(0.5);
  doc.rect(14, 14, pageWidth - 28, pageHeight - 28);

  // Header
  doc.setFontSize(28);
  doc.setTextColor(0, 100, 180);
  doc.text("PII Compliance Certificate", pageWidth / 2, 40, { align: "center" });

  // Divider line
  doc.setDrawColor(0, 100, 180);
  doc.setLineWidth(0.5);
  doc.line(50, 48, pageWidth - 50, 48);

  // Body
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.text("This certifies that a comprehensive PII scan has been completed.", pageWidth / 2, 62, {
    align: "center",
  });

  // Details
  doc.setFontSize(12);
  const startY = 80;
  const lineHeight = 10;
  const details = [
    ["Organization:", data.firmName || "CPA Practice"],
    ["Authorized By:", data.userEmail],
    ["Scan Date:", new Date(data.scanDate).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })],
    ["Files Scanned:", `${data.filesScanned} of ${data.totalFiles}`],
    ["Verification:", data.verificationMethod],
    ["Status:", data.allClean ? "ALL CLEAR - No PII Detected" : "ISSUES REMAINING"],
  ];

  details.forEach(([label, value], i) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 60, startY + i * lineHeight);
    doc.setFont("helvetica", "normal");
    doc.text(value, 130, startY + i * lineHeight);
  });

  // Status badge
  if (data.allClean) {
    doc.setFillColor(0, 160, 0);
    doc.roundedRect(pageWidth / 2 - 35, startY + details.length * lineHeight + 5, 70, 20, 3, 3, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("COMPLIANT", pageWidth / 2, startY + details.length * lineHeight + 18, { align: "center" });
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Generated by PII Scanner | Certificate ID: ${generateCertId(data)}`,
    pageWidth / 2,
    pageHeight - 22,
    { align: "center" }
  );
  doc.text(
    "This certificate confirms PII scan completion. It does not guarantee absolute data security.",
    pageWidth / 2,
    pageHeight - 16,
    { align: "center" }
  );

  return Buffer.from(doc.output("arraybuffer"));
}

function generateCertId(data: CertificateData): string {
  const hash = Buffer.from(`${data.userEmail}-${data.scanDate}`).toString("base64").slice(0, 12);
  return `PII-${hash.toUpperCase()}`;
}
